title = "Front National"
alias = "fn"
candidat = "Marine Le Pen"

[[categories]]
  id = "constitution"
  title = "Constitution et Institutions"

  [[categories.list]]
    title = "Réforme constitutionnelle"

    [categories.list.them]
    quote = "
      <p>Augmenter dès la première année du mandat le budget de la Défense à 2 % du PIB puis tendre vers 3 % à l’horizon de la fin du quinquennat. Ces 2 % minimum seront  inscrits  dans  la  Constitution.</p>
      <p>Défendre l’identité nationale, les valeurs et les traditions de notre civilisation française. Inscrire dans la Constitution la défense et la promotion de notre patrimoine historique et culturel.</p>
      <p>Ériger la citoyenneté française en privilège pour tous les Français par l’inscription dans la Constitution de la priorité nationale.</p>
    "
    ref = "Marine Présidente - 02/2017"
    link = "https://www.marine2017.fr/programme/"
    tldr = "Inscrire dans la Constitution l'augmentation du <strong>budget de la Défense</strong>, le principe de <strong>priorité nationale</strong> et la <strong>défense du patrimoine</strong>."

    [categories.list.us]
    quote = "La nouvelle Constitution dont la France a besoin doit être radicalement nouvelle, y compris dans sa méthode d'écriture : elle ne peut être un simple rafistolage de la 5e République, ni se résumer à quelques réformes octroyées par le futur président de la République. C'est le peuple lui-même qui doit s'emparer de la question et s'impliquer tout au long d'un processus constituant. Nous proposons la convocation d'une assemblée spécifiquement chargée de rédiger une nouvelle Constitution sous le contrôle des citoyens : une Assemblée constituante."
    ref = "L'Avenir En Commun - 01/12/2016"
    link = "https://laec.fr/section/1/reunir-une-assemblee-constituante"
    tldr = "Création d'une Assemblée Constituante pour une <strong>VIe République</strong>."

  [[categories.list]]
    title = "Mode de révision de la Constitution"

    [categories.list.them]
    quote = "Organiser un référendum en vue de réviser la Constitution et conditionner toute révision future de la Constitution à un référendum. Élargir le champ d’application de l’article 11 de la Constitution."
    ref = "Marine Présidente - 02/2017"
    link = "https://www.marine2017.fr/programme/#0"
    tldr = "Toute révision de la Constitution passera par un <strong>référendum</strong>."

    [categories.list.us]
    quote = "Rendre obligatoire le recours au référendum pour réviser la Constitution ou ratifier tout nouveau traité européen et garantir le respect de la décision populaire."
    ref = "L'Avenir En Commun - 01/12/2016"
    link = "https://laec.fr/section/3/une-republique-permettant-l-intervention-populaire"
    tldr = "Toute révision de la Constitution passera par un <strong>référendum</strong>."

  [[categories.list]]
    title = "Droit de Vote"

    [categories.list.them]
    tldr = "<span class=\"empty\">Nous n'avons pas encore trouvé de propositions.</span>"

    [categories.list.us]
    quote = "
    <p>Fixer le droit de vote à 16 ans, instaurer le vote obligatoire et la reconnaissance du vote blanc comme suffrage exprimé et généraliser la représentation proportionnelle.</p>
    <p>Reconnaître le droit de vote aux élections locales pour les résidents étrangers en situation régulière, comme en bénéficient déjà les ressortissants des pays de l'Union européenne.</p>
    "
    ref = "L'Avenir En Commun - 01/12/2016"
    link = "https://laec.fr/section/3/une-republique-permettant-l-intervention-populaire"
    tldr = "Droit de <strong>vote obligatoire</strong> à partir de <strong>16 ans</strong> et reconnaissance du <strong>vote blanc</strong>. Droit de <strong>vote des étrangers</strong> aux élections locales."

  [[categories.list]]
    title = "49.3"

    [categories.list.them]
    tldr = "<span class=\"empty\">Nous n'avons pas encore trouvé de propositions.</span>"

    [categories.list.us]
    quote = "Convoquer un référendum (article 11 de la Constitution) pour engager le processus constituant."
    ref = "L'Avenir En Commun - 01/12/2016"
    link = "https://laec.fr/section/1/reunir-une-assemblee-constituante"
    tldr = "<strong>Nouvelle Constitution</strong>."

  [[categories.list]]
    title = "Contrôle des élu.e.s"

    [categories.list.them]
    tldr = "<span class=\"empty\">Nous n'avons pas encore trouvé de propositions.</span>"

    [categories.list.us]
    quote = "Créer un droit de révoquer un élu en cours de mandat, par référendum, sur demande d'une partie du corps électoral."
    ref = "L'Avenir En Commun - 01/12/2016"
    link = "https://laec.fr/section/3/une-republique-permettant-l-intervention-populaire"
    tldr = "Droit de <strong>révoquer</strong> les élu·e·s."

  [[categories.list]]
    title = "Initiative Populaire"

    [categories.list.them]
    quote = "Créer un véritable référendum d’initiative populaire, sur proposition d’au moins 500 000 électeurs."
    ref = "Marine Présidente - 02/2017"
    link = "https://www.marine2017.fr/programme/#0"
    tldr = "<strong>Référendum</strong> d'initiative populaire."

    [categories.list.us]
    quote = "Instaurer le référendum d'initiative citoyenne et le droit des citoyens de proposer une loi."
    ref = "L'Avenir En Commun - 01/12/2016"
    link = "https://laec.fr/section/3/une-republique-permettant-l-intervention-populaire"
    tldr = "<strong>Référendum</strong> d'initiative populaire."

  [[categories.list]]
    title = "Parité dans les institutions"

    [categories.list.them]
    tldr = "<span class=\"empty\">Nous n'avons pas encore trouvé de propositions.</span>"

    [categories.list.us]
    quote = "Imposer l'égalité de conditions entre les femmes et les hommes dans les institutions politiques, administratives, économiques, syndicales et associatives."
    ref = "L'Avenir En Commun - 01/12/2016"
    link = "https://laec.fr/section/6/une-republique-universelle"
    tldr = "Imposer l'<strong>égalité</strong> des genres dans toutes les institutions."

  [[categories.list]]
    title = "Cumul des mandats"

    [categories.list.them]
    tldr = "<span class=\"empty\">Nous n'avons pas encore trouvé de propositions.</span>"

    [categories.list.us]
    quote = "Rendre effectif le principe du non-cumul des mandats, y compris dans le temps."
    ref = "L'Avenir En Commun - 01/12/2016"
    link = "https://laec.fr/section/3/une-republique-permettant-l-intervention-populaire"
    tldr = "<strong>Non-cumul</strong> des mandats."

  [[categories.list]]
    title = "Corruption et lobbying"

    [categories.list.them]
    tldr = "<span class=\"empty\">Nous n'avons pas encore trouvé de propositions.</span>"

    [categories.list.us]
    quote = "
    <p>Rendre inéligible à vie toute personne condamnée pour corruption.</p>
    <p>Combattre la pollution du débat parlementaire par les lobbies, interdire l'entrée des lobbyistes dans l'enceinte du Parlement et les cadeaux faits aux parlementaires.</p>
    <p>Appliquer les recommandations d'Anticor et de Transparency International visant à empêcher la corruption et à rapprocher les représentants des représentés, notamment obliger un élu à rendre publique sa déclaration de patrimoine transmise à la Haute autorité pour la transparence de la vie publique et supprimer la réserve parlementaire (enveloppe financière dépensée sans vote du Parlement, selon le bon vouloir de chaque parlementaire)</p>
    "
    ref = "L'Avenir En Commun - 01/12/2016"
    link = "https://laec.fr/section/2/balayer-l-oligarchie-abolir-les-privileges-de-la-caste"
    tldr = "<strong>Inéligibilité</strong> des personnes condamnées pour corruption, interdiction des lobbyistes au Parlement, publication de la <strong>déclaration de patrimoine</strong> des élus et suppression de la <strong>réserve parlementaire</strong>."

  [[categories.list]]
    title = "Proportionnelle"

    [categories.list.them]
    quote = "Permettre la représentation de tous les Français par le scrutin proportionnel à toutes les élections. À l’Assemblée nationale, la proportionnelle sera intégrale avec une prime majoritaire de 30 % des sièges pour la liste arrivée en tête et un seuil de 5 % des suffrages pour obtenir des élus."
    ref = "Marine Présidente - 02/2017"
    link = "https://www.marine2017.fr/programme/#0"
    tldr = "Scrutin proportionnel <strong>à toutes les élections</strong>."

    [categories.list.us]
    quote = "Fixer le droit de vote à 16 ans, instaurer le vote obligatoire et la reconnaissance du vote blanc comme suffrage exprimé et généraliser la représentation proportionnelle."
    ref = "L'Avenir En Commun - 01/12/2016"
    link = "https://laec.fr/section/3/une-republique-permettant-l-intervention-populaire"
    tldr = "<strong>Généraliser</strong> la représentation proportionnelle."

  [[categories.list]]
    title = "Administration publique centrale"

    [categories.list.them]
    quote = "Abaisser le nombre de députés à 300 (contre 577 aujourd’hui) et le nombre de sénateurs à 200 (contre 348 aujourd’hui)."
    ref = "Marine Présidente - 02/2017"
    link = "https://www.marine2017.fr/programme/#0"
    tldr = "Abaisser le nombre de <strong>députés à 300</strong> et le nombre de <strong>sénateurs à 200</strong>."

    [categories.list.us]
    quote = "
    <p>Abolir la monarchie présidentielle en instaurant un régime parlementaire stable dans lequel le gouvernement détient le pouvoir exécutif et est responsable devant le Parlement, transférer le pouvoir de nomination au Parlement</p>
    <p>Supprimer le Sénat et le Conseil économique, social et environnemental et créer une Assemblée de l'intervention populaire et du long terme émettant un avis sur l'impact écologique et social des lois</p>
    "
    ref = "L'Avenir En Commun - 01/12/2016"
    link = "https://laec.fr/section/4/abolir-la-monarchie-presidentielle"
    tldr = "<strong>Changement des institutions</strong> par la VIe république."

[[categories]]
  id = "justice"
  title = "Justice et Sécurité"

  [[categories.list]]
    title = "Indépendance du pouvoir judiciaire"

    [categories.list.them]
    tldr = "<span class=\"empty\">Nous n'avons pas encore trouvé de propositions.</span>"

    [categories.list.us]
    quote = "
    <p>Organiser une distinction claire entre les pouvoirs :</p>
    <p>• Fin du « verrou de Bercy » en matière fiscale, c’est-à-dire du pouvoir donné au ministère du Budget de faire obstacle aux poursuites pénales contre les fraudeurs fiscaux. La justice retrouvera ainsi la plénitude de ses compétences.</p>
    <p>• Suppression de la Cour de justice de la République, juridiction d’exception en charge de juger de la responsabilité pénale des ministres (pour les actes commis dans le cadre de leurs fonctions). Composée de 12 parlementaires et 3 magistrats,elle ne présente pas les garanties d’une juridiction indépendante et organise l’impunité des politiques ainsi que l’a montré l’affaire Lagarde.</p>
    <p>• Suppression de la possibilité pour les magistrat·e·s de passer du parquet au « siège », c’est-à-dire d’être procureur puis juge. Il faut mettre fin à cette situation absurde dans laquelle les juges sont tour à tour en position d’accuser et de  juger, ce qui porte évidemment atteinte au principe de l’impartialité du juge du siège.</p>
    <p>• Renforcement de l’indépendance des juges d’instruction par la collégialité et le détachement d’officiers de police judiciaire auprès des juridictions, sur la base du volontariat et pour une période de trois ans renouvelable, afin d’éviter  l’intrusion de la hiérarchie du ministère de l’Intérieur au coeur des enquêtes sensibles.</p>
    "
    ref = "Une justice au nom du peuple - 2017"
    link = "https://avenirencommun.fr/le-livret-justice/"
    tldr = "Renforcer l'<strong>impartialité</strong> et l'<strong>indépendance</strong> de la Justice."

  [[categories.list]]
    title = "Prison"

    [categories.list.them]
    quote = "Instaurer une peine de prison de perpétuité réelle incompressible pour les crimes les plus graves."
    ref = "Marine Présidente - 02/2017"
    link = "https://www.marine2017.fr/programme"
    tldr = "Instaurer la <strong>perpétuité incompressible</strong>."

    [categories.list.us]
    quote = "Garantie du respect des droits des personnes détenues  par le développement du  budget  «réinsertion»  de  l’administration  pénitentiaire,  l’engagement  de  travaux  urgents  de  lutte  contre  l’insalubrité,  la  mise  en  place  d’un  numerus clausus comme mesure transitoire, le respect du droit à l’encellulement individuel, la mise en place de bureaux de vote dans les établissements, le respect du droit du travail pour les détenu·e·s."
    ref = "Une justice au nom du peuple - 2017"
    link = "https://avenirencommun.fr/le-livret-justice/"
    tldr = "<strong>Respect</strong> des droits des personnes détenues, lutte contre l'<strong>insalubrité</strong>."

  [[categories.list]]
    title = "Contrôle au faciès"

    [categories.list.them]
    tldr = "<span class=\"empty\">Nous n'avons pas encore trouvé de propositions.</span>"

    [categories.list.us]
    quote = "Nous  modifierons  la  loi  sur  les  contrôles  d’identité  par  la  police  pour  prendre en compte la récente jurisprudence de la Cour de cassation contre les contrôles au faciès : inversion de la charge de la preuve, réforme de l’article 78-2 du  Code  de  procédure  pénale  pour  rendre  plus  exceptionnels  les  contrôles  d’identité,  obligation  de  délivrance  d’un  récépissé  de  contrôle,  filmage  des  contrôles par la police sous peine de nullité de la procédure qui en découlerait."
    ref = "Sécurité : retour à la raison - 2017"
    link = "https://avenirencommun.fr/le-livret-securite/"
    tldr = "Obligation  de  délivrance  d’un  <strong>récépissé</strong>  de  contrôle,  <strong>filmage</strong>  des  contrôles sous peine de nullité."

  [[categories.list]]
    title = "Sans papiers"

    [categories.list.them]
    quote = "Rendre impossible la régularisation ou la naturalisation des étrangers en situation illégale. Simplifier et automatiser leur expulsion."
    ref = "Marine Présidente - 02/2017"
    link = "https://www.marine2017.fr/programme"
    tldr = "<strong>Interdire</strong> la régularisation et simplifier l'<strong>expulsion</strong> des sans papiers."

    [categories.list.us]
    quote = "Régulariser les travailleurs sans-papiers pour assurer l'égalité sociale entre travailleurs."
    ref = "L'Avenir En Commun - 01/12/2016"
    link = "https://laec.fr/section/25/eradiquer-la-precarite-respecter-les-metiers-et-les-travailleurs"
    tldr = "<strong>Régularisation</strong> des <strong>travailleurs</strong> sans papiers."

  [[categories.list]]
    title = "Renseignement"

    [categories.list.them]
    quote = "Renforcer les moyens humains et techniques des services de renseignement intérieurs et extérieurs."
    ref = "Marine Présidente - 02/2017"
    link = "https://www.marine2017.fr/programme"
    tldr = "Renforcer les <strong>moyens</strong> humains et techniques."

    [categories.list.us]
    quote = "
    • Renforcement du renseignement territorial et humain.<br />
    • Revenir sur la fusion de la DST et des RG.<br />
    • Privilégier l’infiltration, le travail de terrain et le redéploiement intelligent.<br />
    • Renforcer les moyens d’analyses des renseignements collectés.<br />
    • Recrutement d'analystes et de traducteurs en nombre suffisant.<br />
    • Remise en question des pratiques et dispositifs de surveillance de masse sur l’Internet et les réseaux téléphoniques, inefficaces et liberticides. <br />
    • Focalisation du renseignement sur les menaces sécuritaires et économiques hexagonales, et non sur la surveillance des mouvements sociaux.<br />
    • Restauration de l’indépendance nationale en matière de renseignement, via la fin de la tutelle de fait exercée par les agences anglo-saxonnes.<br />
    "
    ref = "Sécurité : retour à la raison - 2017"
    link = "https://avenirencommun.fr/le-livret-securite/"
    tldr = "Renforcer l'<strong>indépendance</strong>, le <strong>renseignement humain</strong> et les <strong>moyens</strong> d'analyse. Recentrer les missions sur les <strong>menaces sécuritaires</strong>."

    [[categories.list]]
      title = "Défense militaire"

      [categories.list.them]
      quote = "Augmenter dès la première année du mandat le budget de la Défense à 2 % du PIB puis tendre vers 3 % à l’horizon de la fin du quinquennat. Ces 2 % minimum seront inscrits dans la Constitution."
      ref = "Marine Présidente - 02/2017"
      link = "https://www.marine2017.fr/programme/"
      tldr = "Porter le budget de la Défense à <strong>2%</strong> puis <strong>3%</strong> du PIB. Inscrire dans la <strong>constitution</strong> 2% minimum du budget de la Défense"

      [categories.list.us]
      quote = "
      <p>Sortir de l'OTAN et refuser la participation de la France à toute alliance militaire permanente à l'exception des opérations de maintien de la paix sous l'égide de l'ONU.</p>
      <p>Rédiger un nouveau Livre blanc et adopter une nouvelle loi de programmation militaire ayant pour objectif la restauration pleine et entière de l'indépendance militaire.</p>
      "
      ref = "L'Avenir En Commun - 01/12/2016"
      link = "https://laec.fr/chapitre/5/pour-l-independance-de-la-france"
      tldr = "Sortie de l'<strong>OTAN</strong>. Restauration de l'<strong>indépendance</strong> militaire."

    [[categories.list]]
      title = "Service civique"

      [categories.list.them]
      quote = "Étendre à la métropole le Service Militaire Adapté sur le modèle de celui en vigueur en Outre-mer."
      ref = "Marine Présidente - 02/2017"
      link = "https://www.marine2017.fr/programme/"
      tldr = "Rétablissement d’un service <strong>militaire</strong> (minimum obligatoire 3 mois)."

      [categories.list.us]
      quote = "
      <p>Le service citoyen obligatoire, c’est neuf mois rémunérés au smic et comprenant une formation militaire initiale avec un droit à l’objection de conscience. Ils’appliquera pour les femmes et pour les hommes, sur tout le territoire, y compris dans les départements d’outre-mer, les zones rurales et les quartiers populaires par conscription avant 25 ans. Ce service sera proche du lieu de vie, en limitant le « casernement » aux fonctions qui l’exigent réellement.</p>
      <p>Les jeunes seront affecté·e·s à des tâches d’intérêt général : secours à la population, sapeurs-pompiers, sécurité publique, défense, sécurité civile, protection et réparation de l’environnement, appui à des associations labellisées d’intérêt général. Participer au service citoyen, c’est être au service de soi et au service de tou·te·s.</p>
      <p>Le service citoyen est aussi un moment de remise à niveau gratuite des jeunes qui ont pu décrocher du système scolaire ou qui sont en difficulté. Il comprend en effet un bilan de santé, une évaluation des capacités d’écriture, de lecture et de calcul avec leur éventuelle mise à niveau, mais aussi la formation gratuite à la conduite et le passage de l’examen du permis de conduire.</p>
      <p>Le service citoyen garantira le droit à changer de corps d’affectation en cas de problèmes manifestes. Les jeunes qui le souhaitent pourront aussi rejoindre la garde nationale, placée sous commandement civil.</p>
      "
      ref = "Pour l'émancipation de la jeunesse - 2017"
      link = "https://avenirencommun.fr/le-livret-jeunesse/"
      tldr = "Service <strong>citoyen rémunéré</strong> et obligatoire de 9 mois."
