title = "Les Républicains"
alias = "lr"
candidat = "François Fillon"

[[categories]]
  id = "constitution"
  title = "Constitution et Institutions"

  [[categories.list]]
    title = "Réforme constitutionnelle"

    [categories.list.them]
    quote = "
    <p>Inscrire dans la Constitution le principe des quotas fixés par la loi, plafonnant le nombre de titres de séjour pouvant être délivrés chaque année au titre de l'immigration professionnelle et familiale, en fonction des capacités d'accueil de la France et des capacités d'intégration des demandeurs.</p>
    <p>Réécrire le principe de précaution, inscrit dans la constitution pour favoriser l’innovation responsable.</p>
    "
    ref = "Mon projet pour la France - 13/03/2017"
    link = "https://www.fillon2017.fr/projet"
    tldr = "Ajouter des <strong>quotats d'immigration</strong> à la Constitution. <strong>Modifier le principe de précaution</strong> visant à protéger environnement et santé."

    [categories.list.us]
    quote = "La nouvelle Constitution dont la France a besoin doit être radicalement nouvelle, y compris dans sa méthode d'écriture : elle ne peut être un simple rafistolage de la 5e République, ni se résumer à quelques réformes octroyées par le futur président de la République. C'est le peuple lui-même qui doit s'emparer de la question et s'impliquer tout au long d'un processus constituant. Nous proposons la convocation d'une assemblée spécifiquement chargée de rédiger une nouvelle Constitution sous le contrôle des citoyens : une Assemblée constituante."
    ref = "L'Avenir En Commun - 01/12/2016"
    link = "https://laec.fr/section/1/reunir-une-assemblee-constituante"
    tldr = "Création d'une <strong>Assemblée Constituante</strong> pour une VIe République."

  [[categories.list]]
    title = "Révision de la Constitution"

    [categories.list.them]
    tldr = "Nous n'avons pas encore trouvé de propositions."

    [categories.list.us]
    quote = "Rendre obligatoire le recours au référendum pour réviser la Constitution ou ratifier tout nouveau traité européen et garantir le respect de la décision populaire."
    ref = "L'Avenir En Commun - 01/12/2016"
    link = "https://laec.fr/section/3/une-republique-permettant-l-intervention-populaire"
    tldr = "Toute révision de la Constitution passera par un <strong>référendum</strong>."

  [[categories.list]]
    title = "Droit de Vote"

    [categories.list.them]
    tldr = "Nous n'avons pas encore trouvé de propositions."

    [categories.list.us]
    quote = "Fixer le droit de vote à 16 ans, instaurer le vote obligatoire et la reconnaissance du vote blanc comme suffrage exprimé et généraliser la représentation proportionnelle."
    ref = "L'Avenir En Commun - 01/12/2016"
    link = "https://laec.fr/section/3/une-republique-permettant-l-intervention-populaire"
    tldr = "Doit de vote <strong>obligatoire</strong> à partir de <strong>16 ans</strong> et reconnaissance du <strong>vote blanc</strong>."

  [[categories.list]]
    title = "49.3"

    [categories.list.them]
    tldr = "Nous n'avons pas encore trouvé de propositions."

    [categories.list.us]
    quote = "Convoquer un référendum (article 11 de la Constitution) pour engager le processus constituant."
    ref = "L'Avenir En Commun - 01/12/2016"
    link = "https://laec.fr/section/1/reunir-une-assemblee-constituante"
    tldr = "Nouvelle Constitution, <strong>VIe République</strong>."

  [[categories.list]]
    title = "Contrôle des élu.e.s"

    [categories.list.them]
    tldr = "Nous n'avons pas encore trouvé de propositions."

    [categories.list.us]
    quote = "Créer un droit de révoquer un élu en cours de mandat, par référendum, sur demande d'une partie du corps électoral."
    ref = "L'Avenir En Commun - 01/12/2016"
    link = "https://laec.fr/section/3/une-republique-permettant-l-intervention-populaire"
    tldr = "Droit de <strong>révoquer</strong> les élu·e·s."

  [[categories.list]]
    title = "Initiative Populaire"

    [categories.list.them]
    tldr = "Nous n'avons pas encore trouvé de propositions."

    [categories.list.us]
    quote = "Instaurer le référendum d'initiative citoyenne et le droit des citoyens de proposer une loi."
    ref = "L'Avenir En Commun - 01/12/2016"
    link = "https://laec.fr/section/3/une-republique-permettant-l-intervention-populaire"
    tldr = "<strong>Référendum</strong> d'initiative populaire."

  [[categories.list]]
    title = "Parité dans les institutions"

    [categories.list.them]
    quote = "S’engager pour un gouvernement paritaire."
    ref = "Mon projet pour la France - 13/03/2017"
    link = "https://www.fillon2017.fr/projet/femmes/"
    tldr = "<strong>Engagement</strong> pour l'égalité des genres au <strong>gouvernement</strong>."

    [categories.list.us]
    quote = "Imposer l'égalité de conditions entre les femmes et les hommes dans les institutions politiques, administratives, économiques, syndicales et associatives."
    ref = "L'Avenir En Commun - 01/12/2016"
    link = "https://laec.fr/section/6/une-republique-universelle"
    tldr = "<strong>Imposer</strong> l'égalité des genres dans <strong>toutes les institutions</strong>."

  [[categories.list]]
    title = "Cumul des mandats"

    [categories.list.them]
    quote = "Conserver la loi sur le non cumul des mandats, qui permettra d’avoir des parlementaires à plein temps concentrés sur la rédaction des lois et le contrôle du gouvernement."
    ref = "Mon projet pour la France - 13/03/2017"
    link = "https://www.fillon2017.fr/projet/institutions/"
    tldr = "Status Quo."

    [categories.list.us]
    quote = "Rendre effectif le principe du non-cumul des mandats, y compris dans le temps."
    ref = "L'Avenir En Commun - 01/12/2016"
    link = "https://laec.fr/section/3/une-republique-permettant-l-intervention-populaire"
    tldr = "<strong>Non-cumul</strong> des mandats."

  [[categories.list]]
    title = "Emploi de membres de la famille"

    [categories.list.them]
    quote = "Instituer la transparence totale par la publication obligatoire des liens de parenté entre les parlementaires et les collaborateurs (y compris en cas de recrutement croisé)."
    ref = "Mon projet pour la France - 13/03/2017"
    link = "https://www.fillon2017.fr/projet/institutions/"
    tldr = "<strong>Transparence</strong> des parlementaires sur l'emploi de membre de sa famille."

    [categories.list.us]
    tldr = "Nous n'avons pas encore trouvé de propositions."

  [[categories.list]]
    title = "Corruption et lobbying"

    [categories.list.them]
    quote = "Inciter les assemblées à réformer et à améliorer les mécanismes de contrôle de déontologie mis en place dans chacune d’elles."
    ref = "Mon projet pour la France - 13/03/2017"
    link = "https://www.fillon2017.fr/projet/institutions/"
    tldr = "<strong>Incitation</strong> à améliorer le contrôle des parlementaires."

    [categories.list.us]
    quote = "
    <p>Rendre inéligible à vie toute personne condamnée pour corruption.</p>
    <p>Combattre la pollution du débat parlementaire par les lobbies, interdire l'entrée des lobbyistes dans l'enceinte du Parlement et les cadeaux faits aux parlementaires.</p>
    <p>Appliquer les recommandations d'Anticor et de Transparency International visant à empêcher la corruption et à rapprocher les représentants des représentés, notamment obliger un élu à rendre publique sa déclaration de patrimoine transmise à la Haute autorité pour la transparence de la vie publique et supprimer la réserve parlementaire (enveloppe financière dépensée sans vote du Parlement, selon le bon vouloir de chaque parlementaire)</p>
    "
    ref = "L'Avenir En Commun - 01/12/2016"
    link = "https://laec.fr/section/2/balayer-l-oligarchie-abolir-les-privileges-de-la-caste"
    tldr = "<strong>Inéligibilité</strong> des personnes condamnées pour corruption, interdiction des lobbyistes au Parlement, publication de la <strong>déclaration de patrimoine</strong> des élus et suppression de la <strong>réserve parlementaire</strong>."

  [[categories.list]]
    title = "Administration publique centrale"

    [categories.list.them]
    quote = "Proposer aux Français par référendum, une réduction du nombre de parlementaires, à environ 400 députés et 200 sénateurs afin de donner à ceux-ci les moyens nécessaires pour exercer leur fonction."
    ref = "Mon projet pour la France - 13/03/2017"
    link = "https://www.fillon2017.fr/projet/institutions/"
    tldr = "<strong>Abaisser</strong> le nombre de députés à 400 et le nombre de sénateurs à 200 sur <strong>référendum</strong>."

    [categories.list.us]
    quote = "
    <p>Abolir la monarchie présidentielle en instaurant un régime parlementaire stable dans lequel le gouvernement détient le pouvoir exécutif et est responsable devant le Parlement, transférer le pouvoir de nomination au Parlement</p>
    <p>Supprimer le Sénat et le Conseil économique, social et environnemental et créer une Assemblée de l'intervention populaire et du long terme émettant un avis sur l'impact écologique et social des lois</p>
    "
    ref = "L'Avenir En Commun - 01/12/2016"
    link = "https://laec.fr/section/4/abolir-la-monarchie-presidentielle"
    tldr = "<strong>Changement des institutions</strong> par la VIe république."
