[[categories]]
  id = "constitution"
  title = "Constitution et Institutions"

  [[categories.list]]
    title = "Réforme constitutionnelle"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "La nouvelle Constitution dont la France a besoin doit être radicalement nouvelle, y compris dans sa méthode d'écriture : elle ne peut être un simple rafistolage de la 5e République, ni se résumer à quelques réformes octroyées par le futur président de la République. C'est le peuple lui-même qui doit s'emparer de la question et s'impliquer tout au long d'un processus constituant. Nous proposons la convocation d'une assemblée spécifiquement chargée de rédiger une nouvelle Constitution sous le contrôle des citoyens : une Assemblée constituante."
    ref = "L'Avenir En Commun - 01/12/2016"
    link = "https://laec.fr/section/1/reunir-une-assemblee-constituante"
    tldr = "Création d'une Assemblée Constituante pour une VIe République."

  [[categories.list]]
    title = "Révision de la Constitution"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "Rendre obligatoire le recours au référendum pour réviser la Constitution ou ratifier tout nouveau traité européen et garantir le respect de la décision populaire."
    ref = "L'Avenir En Commun - 01/12/2016"
    link = "https://laec.fr/section/3/une-republique-permettant-l-intervention-populaire"
    tldr = "Toute révision de la Constitution passera par un référendum."

  [[categories.list]]
    title = "Droit de Vote"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "
    <p>Fixer le droit de vote à 16 ans, instaurer le vote obligatoire et la reconnaissance du vote blanc comme suffrage exprimé et généraliser la représentation proportionnelle.</p>
    <p>Reconnaître le droit de vote aux élections locales pour les résidents étrangers en situation régulière, comme en bénéficient déjà les ressortissants des pays de l'Union européenne.</p>
    "
    ref = "L'Avenir En Commun - 01/12/2016"
    link = "https://laec.fr/section/3/une-republique-permettant-l-intervention-populaire"
    tldr = "Droit de vote obligatoire à partir de 16 ans et reconnaissance du vote blanc. Droit de vote des étrangers aux élections locales."

  [[categories.list]]
    title = "49.3"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "Convoquer un référendum (article 11 de la Constitution) pour engager le processus constituant."
    ref = "L'Avenir En Commun - 01/12/2016"
    link = "https://laec.fr/section/1/reunir-une-assemblee-constituante"
    tldr = "Nouvelle Constitution, VIe République."

  [[categories.list]]
    title = "Initiative Populaire"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "Instaurer le référendum d'initiative citoyenne et le droit des citoyens de proposer une loi."
    ref = "L'Avenir En Commun - 01/12/2016"
    link = "https://laec.fr/section/3/une-republique-permettant-l-intervention-populaire"
    tldr = "Référendum d'initiative populaire."

  [[categories.list]]
    title = "Parité dans les institutions"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "Imposer l'égalité de conditions entre les femmes et les hommes dans les institutions politiques, administratives, économiques, syndicales et associatives."
    ref = "L'Avenir En Commun - 01/12/2016"
    link = "https://laec.fr/section/6/une-republique-universelle"
    tldr = "Imposer l'égalité des genres dans toutes les institutions."

  [[categories.list]]
    title = "Cumul des mandats"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "Rendre effectif le principe du non-cumul des mandats, y compris dans le temps."
    ref = "L'Avenir En Commun - 01/12/2016"
    link = "https://laec.fr/section/3/une-republique-permettant-l-intervention-populaire"
    tldr = "Non-cumul des mandats."

  [[categories.list]]
    title = "Contrôle des élu.e.s"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "Créer un droit de révoquer un élu en cours de mandat, par référendum, sur demande d'une partie du corps électoral."
    ref = "L'Avenir En Commun - 01/12/2016"
    link = "https://laec.fr/section/3/une-republique-permettant-l-intervention-populaire"
    tldr = "Droit de révoquer les élu·e·s."

  [[categories.list]]
    title = "Emploi de membres de la famille"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]

  [[categories.list]]
    title = "Corruption et lobbying"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "
    <p>Rendre inéligible à vie toute personne condamnée pour corruption.</p>
    <p>Combattre la pollution du débat parlementaire par les lobbies, interdire l'entrée des lobbyistes dans l'enceinte du Parlement et les cadeaux faits aux parlementaires.</p>
    <p>Appliquer les recommandations d'Anticor et de Transparency International visant à empêcher la corruption et à rapprocher les représentants des représentés, notamment obliger un élu à rendre publique sa déclaration de patrimoine transmise à la Haute autorité pour la transparence de la vie publique et supprimer la réserve parlementaire (enveloppe financière dépensée sans vote du Parlement, selon le bon vouloir de chaque parlementaire)</p>
    "
    ref = "L'Avenir En Commun - 01/12/2016"
    link = "https://laec.fr/section/2/balayer-l-oligarchie-abolir-les-privileges-de-la-caste"
    tldr = "<strong>Inéligibilité</strong> des personnes condamnées pour corruption, interdiction des lobbyistes au Parlement, publication de la <strong>déclaration de patrimoine</strong> des élus et suppression de la <strong>réserve parlementaire</strong>."

  [[categories.list]]
    title = "Pantouflage"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "Mettre fin au pantouflage : tout haut fonctionnaire souhaitant travailler dans le privé devra démissionner de la fonction publique et rembourser le prix de sa formation s'il n'a pas servi au moins dix ans, supprimer le concours externe de l'ENA pour toute personne n'ayant jamais travaillé, durcir les règles contre les conflits d'intérêts, allonger les périodes d'interdiction d'exercer une fonction privée après avoir exercé une activité publique dans le même secteur."
    ref = "L'Avenir En Commun - 01/12/2016"
    link = "https://laec.fr/section/2/balayer-l-oligarchie-abolir-les-privileges-de-la-caste"
    tldr = "Tout haut fonctionnaire souhaitant travailler dans le privé devra démissionner de la fonction publique."

  [[categories.list]]
    title = "Proportionnelle"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "Fixer le droit de vote à 16 ans, instaurer le vote obligatoire et la reconnaissance du vote blanc comme suffrage exprimé et généraliser la représentation proportionnelle."
    ref = "L'Avenir En Commun - 01/12/2016"
    link = "https://laec.fr/section/3/une-republique-permettant-l-intervention-populaire"
    tldr = "Généraliser la représentation proportionnelle."

  [[categories.list]]
    title = "Administration publique centrale"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "
    <p>Abolir la monarchie présidentielle en instaurant un régime parlementaire stable dans lequel le gouvernement détient le pouvoir exécutif et est responsable devant le Parlement, transférer le pouvoir de nomination au Parlement</p>
    <p>Supprimer le Sénat et le Conseil économique, social et environnemental et créer une Assemblée de l'intervention populaire et du long terme émettant un avis sur l'impact écologique et social des lois</p>
    "
    ref = "L'Avenir En Commun - 01/12/2016"
    link = "https://laec.fr/section/4/abolir-la-monarchie-presidentielle"
    tldr = "<strong>Changement des institutions</strong> par la VIe république."
