[[categories]]
  id = "culture"
  title = "Culture et Médias"

  [[categories.list]]
    title = "Budget"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "<p>Porter le budget consacré à l'art, à la culture et à la création à 1 % du PIB chaque année pour :<br />
    • Pérenniser le régime des intermittents du spectacle sur la base de l'accord du 28 avril 2016 et l'étendre aux professions artistiques précaires<br />
    • Soutenir la création, le spectacle vivant, et l'appropriation par tous des œuvres et pratiques culturelles, et ce par le renouveau de l'éducation artistique à l'école et dans les conservatoires, de l'éducation populaire et de la culture en entreprise </p>
    <p>Note : Avec cette mesure, le budget 2017 de la culture aurait été de 21.18 milliards d'euros (en prenant le PIB de 2016 de 2 118 milliards d'euros), contre les 7,701 milliards actuellement.</p>"
    ref = "L'Avenir En Commun - 01/12/2016"
    link = "https://laec.fr/s77"
    tldr = "Porter le budget de la Culture à 1 % du PIB chaque année."

  [[categories.list]]
    title = "Musées"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "Étendre la gratuité dans les musées et les autres lieux culturels recevant des subventions publiques nationales, à commencer par un accès gratuit tous les dimanches."
    ref = "Les arts insoumis, la culture en commun - 2017"
    link = "https://avenirencommun.fr/le-livret-culture/"
    tldr = "Étendre la gratuité des musées recevant des subventions publiques nationales."

  [[categories.list]]
    title = "Lieux culturels"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "<p>Mettre les associations au coeur de l’action culturelle sur tout le territoire dans l'espace public. Leur donner par des conventionnements durables les moyens financiers adaptés afin de remédier à l'absence d'équipements culturels.</p>
    <p>Jumeler tous les établissements (écoles, collèges, lycées) avec des établissements culturels, dans des projets profitant à tou·te·s les élèves et encourager les pratiques artistiques collectives ; favoriser la médiation socioculturelle dans ces établissements.</p>
    <p>Favoriser et promouvoir la médiation culturelle dans l’ensemble des lieux patrimoniaux et institutions culturelles subventionnés (musées, orchestres, théâtres, etc.), notamment en leur faisant obligation de recourir à des guidesconférencier·e·s diplômé·e·s et titulaires de la carte professionnelle. Encourager, dans les critères de subvention, la co-construction de la programmation culturelle avec les publics pour une participation active de chacun·e à la vie sociale et culturelle.</p>
    <p>Défendre le maillage national des bibliothèques et médiathèques, garantir leur budget face aux choix financiers ou idéologiques de certaines collectivités territoriales et embaucher des professionnel·le·s pour assurer de plus larges ouvertures</p>"
    ref = "Les arts insoumis, la culture en commun - 2017"
    link = "https://avenirencommun.fr/le-livret-culture/"
    tldr = "Donner par des conventionnements durables aux associations. Jumeler tous les établissement scolaires avec des établissements culturels. Défendre le maillage national des bibliothèques et médiathèques et garantir leur budget."

  [[categories.list]]
    title = "Éducation artistique"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "<p>Faire de l'éducation artistique une vraie priorité de la maternelle à l'université, jusqu'en entreprise. La mettre dans toute sa diversité et dans ses trois dimensions au coeur de l'enseignement artistique (fréquentation des oeuvres, pratique, acquisition des connaissances).</p>
    <p>Transformer l’enseignement artistique supérieur en véritable service public national : sortir les écoles d’art et les conservatoires de musique et de danse du statut inadapté d’Établissement public de coopération culturelle (EPCC). L’État définira les programmes et les règles applicables aux personnels.</p>
    <p>Soutenir les conservatoires de musique, de danse et d'art dramatique dans leur mission d'ouverture à tous les publics et en créer de nouveaux. Mettre fin à la précarité des enseignant·e·s de ces établissements.</p>
    <p>Développer une filière de la création numérique dans l'enseignement professionnel.</p>"
    ref = "Les arts insoumis, la culture en commun - 2017"
    link = "https://avenirencommun.fr/le-livret-culture/"
    tldr = "Faire de l'éducation artistique une vraie priorité. Soutenir les conservatoires. Développer une filière de la création numérique dans l'enseignement professionnel."

  [[categories.list]]
    title = "Intermittents"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "<p>Pérenniser le régime des intermittent·e·s du spectacle sur la base de l’accord du 28 avril 2016. Il est une garantie de la liberté de création de celles et ceux qui y cotisent.</p>
    <p>Étendre ce régime aux professions artistiques précaires, dont les artistes visuels.</p>"
    ref = "Les arts insoumis, la culture en commun - 2017"
    link = "https://avenirencommun.fr/le-livret-culture/"
    tldr = "Pérenniser le régime des intermittent·e·s et l'étendre aux professions artistiques précaires."

  [[categories.list]]
    title = "Domaine public commun"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "Instituer un domaine public commun constitué de l'ensemble des oeuvres qui désormais ne seront plus soumises aux droits d'auteur, afin de participer au financement du régime de sécurité sociale pour les artistes précaires."
    ref = "Les arts insoumis, la culture en commun - 2017"
    link = "https://avenirencommun.fr/le-livret-culture/"
    tldr = "Financer une sécurité sociale pour les artistes par une cotisation sur la vente d'œuvres du domaine public."

  [[categories.list]]
    title = "Défense de la francophonie"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "
    <p>Réorganiser les institutions de la francophonie en agissant pour son recentrage sur la défense, le rayonnement de la langue et son usage commun.</p>
    <p>Renforcer la présence des auteurs francophones ultra-marins et étrangers dans les programmes scolaires.</p>
    <p>Élaborer des contenus éducatifs et des diplômes communs entre pays francophones.</p>
    <p>Développer au moins une revue scientifique internationale digne de ce nom en français.</p>
    <p>Défendre l'usage du français dans les institutions internationales à commencer par l'Union Européenne.</p>
    <p>Renforcer les médias audiovisuels francophones (RFI, France 24 et TV5 Monde) et les mettre en partage avec la communauté francophone.</p>
    "
    ref = "L'Avenir En Commun - 01/12/2016"
    link = "https://laec.fr/s64"
    tldr = "Mettre en valeur, diffuser et multiplier les usages du français et les liens entre ceux qui l'ont en usage commun."

  [[categories.list]]
    title = "Programme d'échange francophone"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "<p>A l'intérieur de l’espace francophone, mettre en place progressivement un visa privilégié permettant la libre circulation en son sein des artistes, des universitaires, des chercheur·se·s, des ingénieur·e·s, des acteur·trice·s économiques et des étudiant·e·s. Comme première concrétisation de ce projet, créer un programme de mobilité étudiante francophone du type Erasmus ; établir un fonds commun des pays francophones en faveur du financement de ce programme.
    </p>
    <p>Renforcer le réseau des Instituts/Alliances français dans les pays non francophones et planifier les échanges d'étudiants et de lycéens</p>"
    ref = "L'Avenir En Commun - 01/12/2016"
    link = "https://laec.fr/s64"
    tldr = "Mise en place d'un VISA francophone privilégié. Renforcer le réseau des Instituts/Alliances français."
