[[categories]]
  id = "culture"
  title = "Médias, Culture et Sport"

  [[categories.list]]
    title = "Anti-concentration / indépendance"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "<p>Adopter une loi anti-concentration des médias, protégeant le secteur des intérêts financiers, favorisant la transformation des médias en coopératives de salariés et de lecteurs/auditeurs/téléspectateurs et attribuer des fréquences aux médias locaux et associatifs.</p>
    <p>Protéger les sources et l'indépendance des rédactions à l'égard des pouvoirs économiques et politiques par le renforcement du statut juridique des rédactions et une charte déontologique dans la convention collective.</p>"
    ref = "L'Avenir En Commun - 01/12/2016"
    link = "https://laec.fr/s8"
    tldr = "Adopter une loi anti-concentration des médias. Protéger l'indépendance des rédactions à l'égard des pouvoirs économiques et politiques."

  [[categories.list]]
    title = "Médias publics"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "
    <p>Élire, par le Parlement, les président·e·s de l’audiovisuel public (France Télévision, Radio France, France Médias Monde) à l’issue d’une campagne publique de présentation des candidat·e·s et des projets en compétition.</p>
    <p>Nous réaffirmerons la volonté politique d’un service public audiovisuel valorisant la création culturelle, le pluralisme démocratique et la diversité.</p>
    <p>La fonction sociale de la télévision et de la radio ne peut être soumise aux aléas du marché et de la finance.</p>
    <p>Les nouveaux usages de la télévision et la convergence des médias, sur de nouveaux supports, comme les box, les tablettes, les smartphones, appellent à la définition d’un cadre réglementaire capable de résister à l’émergence de quelques monopoles, tant anglo-saxons que français, dans la production et la circulation de programmes.</p>
    "
    ref = "Des médias au service du peuple - 2017"
    link = "https://avenirencommun.fr/le-livret-medias"
    tldr = "Élection des président·e·s de l’audiovisuel public par le Parlement. Valorisation de la création culturelle et du pluralisme démocratique."

  [[categories.list]]
    title = "Budget de la Culture"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "<p>Porter le budget consacré à l'art, à la culture et à la création à 1 % du PIB chaque année pour :<br />
    • Pérenniser le régime des intermittents du spectacle sur la base de l'accord du 28 avril 2016 et l'étendre aux professions artistiques précaires<br />
    • Soutenir la création, le spectacle vivant, et l'appropriation par tous des œuvres et pratiques culturelles, et ce par le renouveau de l'éducation artistique à l'école et dans les conservatoires, de l'éducation populaire et de la culture en entreprise </p>
    <p>Note : Avec cette mesure, le budget 2017 de la culture aurait été de 21.18 milliards d'euros (en prenant le PIB de 2016 de 2 118 milliards d'euros), contre les 7,701 milliards actuellement.</p>"
    ref = "L'Avenir En Commun - 01/12/2016"
    link = "https://laec.fr/s77"
    tldr = "Porter le budget de la Culture à 1 % du PIB chaque année."

  [[categories.list]]
    title = "Musées"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "Étendre la gratuité dans les musées et les autres lieux culturels recevant des subventions publiques nationales, à commencer par un accès gratuit tous les dimanches."
    ref = "Les arts insoumis, la culture en commun - 2017"
    link = "https://avenirencommun.fr/le-livret-culture/"
    tldr = "Étendre la gratuité des musées recevant des subventions publiques nationales."

  [[categories.list]]
    title = "Lieux culturels"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "<p>Mettre les associations au coeur de l’action culturelle sur tout le territoire dans l'espace public. Leur donner par des conventionnements durables les moyens financiers adaptés afin de remédier à l'absence d'équipements culturels.</p>
    <p>Jumeler tous les établissements (écoles, collèges, lycées) avec des établissements culturels, dans des projets profitant à tou·te·s les élèves et encourager les pratiques artistiques collectives ; favoriser la médiation socioculturelle dans ces établissements.</p>
    <p>Favoriser et promouvoir la médiation culturelle dans l’ensemble des lieux patrimoniaux et institutions culturelles subventionnés (musées, orchestres, théâtres, etc.), notamment en leur faisant obligation de recourir à des guidesconférencier·e·s diplômé·e·s et titulaires de la carte professionnelle. Encourager, dans les critères de subvention, la co-construction de la programmation culturelle avec les publics pour une participation active de chacun·e à la vie sociale et culturelle.</p>
    <p>Défendre le maillage national des bibliothèques et médiathèques, garantir leur budget face aux choix financiers ou idéologiques de certaines collectivités territoriales et embaucher des professionnel·le·s pour assurer de plus larges ouvertures</p>"
    ref = "Les arts insoumis, la culture en commun - 2017"
    link = "https://avenirencommun.fr/le-livret-culture/"
    tldr = "Donner par des conventionnements durables aux associations. Jumeler tous les établissement scolaires avec des établissements culturels. Défendre le maillage national des bibliothèques et médiathèques et garantir leur budget."

  [[categories.list]]
    title = "Éducation artistique"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "<p>Faire de l'éducation artistique une vraie priorité de la maternelle à l'université, jusqu'en entreprise. La mettre dans toute sa diversité et dans ses trois dimensions au coeur de l'enseignement artistique (fréquentation des oeuvres, pratique, acquisition des connaissances).</p>
    <p>Transformer l’enseignement artistique supérieur en véritable service public national : sortir les écoles d’art et les conservatoires de musique et de danse du statut inadapté d’Établissement public de coopération culturelle (EPCC). L’État définira les programmes et les règles applicables aux personnels.</p>
    <p>Soutenir les conservatoires de musique, de danse et d'art dramatique dans leur mission d'ouverture à tous les publics et en créer de nouveaux. Mettre fin à la précarité des enseignant·e·s de ces établissements.</p>
    <p>Développer une filière de la création numérique dans l'enseignement professionnel.</p>"
    ref = "Les arts insoumis, la culture en commun - 2017"
    link = "https://avenirencommun.fr/le-livret-culture/"
    tldr = "Faire de l'éducation artistique une vraie priorité. Soutenir les conservatoires. Développer une filière de la création numérique dans l'enseignement professionnel."

  [[categories.list]]
    title = "Intermittents"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "<p>Pérenniser le régime des intermittent·e·s du spectacle sur la base de l’accord du 28 avril 2016. Il est une garantie de la liberté de création de celles et ceux qui y cotisent.</p>
    <p>Étendre ce régime aux professions artistiques précaires, dont les artistes visuels.</p>"
    ref = "Les arts insoumis, la culture en commun - 2017"
    link = "https://avenirencommun.fr/le-livret-culture/"
    tldr = "Pérenniser le régime des intermittent·e·s et l'étendre aux professions artistiques précaires."

  [[categories.list]]
    title = "Domaine public commun"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "Instituer un domaine public commun constitué de l'ensemble des oeuvres qui désormais ne seront plus soumises aux droits d'auteur, afin de participer au financement du régime de sécurité sociale pour les artistes précaires."
    ref = "Les arts insoumis, la culture en commun - 2017"
    link = "https://avenirencommun.fr/le-livret-culture/"
    tldr = "Financer une sécurité sociale pour les artistes par une cotisation sur la vente d'œuvres du domaine public."

  [[categories.list]]
    title = "Défense de la francophonie"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "
    <p>Réorganiser les institutions de la francophonie en agissant pour son recentrage sur la défense, le rayonnement de la langue et son usage commun.</p>
    <p>Renforcer la présence des auteurs francophones ultra-marins et étrangers dans les programmes scolaires.</p>
    <p>Élaborer des contenus éducatifs et des diplômes communs entre pays francophones.</p>
    <p>Développer au moins une revue scientifique internationale digne de ce nom en français.</p>
    <p>Défendre l'usage du français dans les institutions internationales à commencer par l'Union Européenne.</p>
    <p>Renforcer les médias audiovisuels francophones (RFI, France 24 et TV5 Monde) et les mettre en partage avec la communauté francophone.</p>
    "
    ref = "L'Avenir En Commun - 01/12/2016"
    link = "https://laec.fr/s64"
    tldr = "Mettre en valeur, diffuser et multiplier les usages du français et les liens entre ceux qui l'ont en usage commun."

  [[categories.list]]
    title = "Programme d'échange francophone"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "<p>A l'intérieur de l’espace francophone, mettre en place progressivement un visa privilégié permettant la libre circulation en son sein des artistes, des universitaires, des chercheur·se·s, des ingénieur·e·s, des acteur·trice·s économiques et des étudiant·e·s. Comme première concrétisation de ce projet, créer un programme de mobilité étudiante francophone du type Erasmus ; établir un fonds commun des pays francophones en faveur du financement de ce programme.
    </p>
    <p>Renforcer le réseau des Instituts/Alliances français dans les pays non francophones et planifier les échanges d'étudiants et de lycéens</p>"
    ref = "L'Avenir En Commun - 01/12/2016"
    link = "https://laec.fr/s64"
    tldr = "Mise en place d'un VISA francophone privilégié. Renforcer le réseau des Instituts/Alliances français."

  [[categories.list]]
    title = "HADOPI"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "
    <p>Supprimer la Hadopi, qui n'a pas fonctionné, et mettre en place un nouveau cadre du partage numérique de la culture par :<br />
    • L'instauration d'une cotisation universelle sur les abonnements internet, finançant la création et ouvrant droit en contrepartie au téléchargement non marchand.<br />
    • La création d'un service public nouveau de l'internet et d'une médiathèque publique en ligne, avec une plate-forme publique d'offre légale en ligne de musique, films et contenus culturels.</p>
    "
    ref = "L'Avenir En Commun - 01/12/2016"
    link = "https://laec.fr/s77"
    tldr = "Remplacer Hadopi par une cotisation universelle sur les abonnements internet ouvrant droit en contrepartie au téléchargement non marchand via une médiathèque publique en ligne."

  [[categories.list]]
    title = "Protection des données personnelles"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "Protéger les données personnelles contre leur utilisation mercantile"
    ref = "L'Avenir En Commun - 01/12/2016"
    link = "https://laec.fr/s83"
    tldr = "Protéger les données personnelles contre leur utilisation mercantile."

  [[categories.list]]
    title = "Généraliser la pratique sportive"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "
    <p>Développer le sport comme moyen d’insertion professionnelle et soutenir toutes les initiatives visant à faire du sport un vecteur de réinsertion des jeunes en difficulté en termes d’accès au travail, en s’appuyant sur des acteur·trice·s associatif·ve·s et privé·e·s, et veiller à ce que ces dispositifs fassent une large part au public féminin et aux publics en situation de handicap.</p>
    <p>Favoriser la gratuité pour les populations modestes et promouvoir la fixation des coûts d’accès en fonction des revenus et de la taille des familles.</p>"
    ref = "Le livret Sport - 2017"
    link = "https://avenirencommun.fr/le-livret-sport/"
    tldr = "Favoriser la gratuité pour les populations modestes et l'accès au public féminin et en situation de handicap."

  [[categories.list]]
    title = "Infrastructures sportives"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "Élaborer un plan national d’urgence pour la construction et la rénovation des équipements sportifs (stades, piscines et gymnases notamment), en partenariat avec les collectivités territoriales (dont les dotations seront « dégelées ») et dans le respect de normes environnementales fortes, pour réduire les inégalités et stopper la concurrence entre les territoires."
    ref = "Le livret Sport - 2017"
    link = "https://avenirencommun.fr/le-livret-sport/"
    tldr = "Élaborer un plan national d’urgence pour la construction et la rénovation des équipements sportifs."

  [[categories.list]]
    title = "Encadrement sportif"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "
    <p>Réaffirmer le rôle des professeurs d'EPS dans la transmission d'une éducation physique obligatoire pour toutes et tous.</p>
    <p>Recruter des éducateur·trice·s physiques ou sportif·ve·s en nombre suffisant afin d’assurer les missions de rééquilibrage des territoires, de garantir l’accessibilité de la pratique sportive et la structuration pérenne des  associations.</p>"
    ref = "Le livret Sport - 2017"
    link = "https://avenirencommun.fr/le-livret-sport/"
    tldr = "Recruter des intervenants sportifs et réaffirmer l'importance de leur rôle à l'école et dans les associations."

  [[categories.list]]
    title = "Sport-Santé"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "
    <p>Développer le sport-santé et l’activité physique adaptée sur ordonnance en formant les médecins.</p>
    <p>Inciter au développement de la pratique de l’activité physique au sein des entreprises et sur les lieux de travail en général.</p>"
    ref = "Le livret Sport - 2017"
    link = "https://avenirencommun.fr/le-livret-sport/"
    tldr = "Développer le sport-santé et la pratique de l’activité physique au sein des entreprises."

  [[categories.list]]
    title = "Sport de haut niveau"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "Renforcer les liens de solidarité entre le sport pour tous et le sport de haut niveau, entre les secteurs amateur et professionnel, augmenter la taxation sur les retransmissions sportives à la télévision (taxe Buffet), pour financer le sport amateur, démocratiser la gestion des fédérations sportives et assurer la souveraineté des licenciés sur leur fédération."
    ref = "L'Avenir En Commun - 01/12/2016"
    link = "https://laec.fr/s78"
    tldr = "Renforcer les liens de solidarité entre le sport pour tous et le sport de haut niveau, démocratiser la gestion des fédérations sportives."
