[[categories]]
  id = "justice"
  title = "Justice et Sécurité"

  [[categories.list]]
    title = "Indépendance du pouvoir judiciaire"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "
    <p>Organiser une distinction claire entre les pouvoirs :</p>
    <p>• Fin du « verrou de Bercy » en matière fiscale, c’est-à-dire du pouvoir donné au ministère du Budget de faire obstacle aux poursuites pénales contre les fraudeurs fiscaux. La justice retrouvera ainsi la plénitude de ses compétences.</p>
    <p>• Suppression de la Cour de justice de la République, juridiction d’exception en charge de juger de la responsabilité pénale des ministres (pour les actes commis dans le cadre de leurs fonctions). Composée de 12 parlementaires et 3 magistrats,elle ne présente pas les garanties d’une juridiction indépendante et organise l’impunité des politiques ainsi que l’a montré l’affaire Lagarde.</p>
    <p>• Suppression de la possibilité pour les magistrat·e·s de passer du parquet au « siège », c’est-à-dire d’être procureur puis juge. Il faut mettre fin à cette situation absurde dans laquelle les juges sont tour à tour en position d’accuser et de  juger, ce qui porte évidemment atteinte au principe de l’impartialité du juge du siège.</p>
    <p>• Renforcement de l’indépendance des juges d’instruction par la collégialité et le détachement d’officiers de police judiciaire auprès des juridictions, sur la base du volontariat et pour une période de trois ans renouvelable, afin d’éviter  l’intrusion de la hiérarchie du ministère de l’Intérieur au coeur des enquêtes sensibles.</p>
    "
    ref = "Une justice au nom du peuple - 2017"
    link = "https://avenirencommun.fr/le-livret-justice/"
    tldr = "Renforcer l'impartialité et l'indépendance de la Justice."

  [[categories.list]]
    title = "Mission de la police"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "
    <p>En matière de sécurité, nos maître-mots sont prévention, dissuasion, sanction.</p>
    <p>Restaurer la police de proximité en refondant les objectifs des polices municipales et affirmant la distinction entre les missions nationales et locales.</p>
    <p>La République a besoin d'une police républicaine, agissant pour protéger les libertés individuelles et collectives. La politique de sécurité doit être refondée en lien avec la population, par l'intégration des conscrits, loin des coups de menton et du deux poids deux mesures. </p>
    <p>L’absurde politique du chiffre mise en place par Sarkozy n’a fait que se poursuivre depuis 2012. La « bâtonnite » (action qui vise à mettre des bâtons dans les cases) continue comme avant, avec à la clef de belles primes pour la haute hiérarchie, en complète déconnexion avec la réalité du terrain.</p>
    <p>L’interdiction immédiate des tasers et flashball et la refondation de la doctrine du maintien de l’ordre pour favoriser la désescalade et la prévention des actes violents. Nous devons démonter les engrenages de violence de deux camps qui s’affrontent. Ainsi seront évités les drames de manifestants choqués, blessés, éborgnés, et des fonctionnaires épuisés, blessés et ayant le sentiment d’être instrumentalisés par le pouvoir politique. </p>
    <p>Le démantèlement des brigades anti-criminalité (BAC) limitera la spécialisation d’unités qui ne font que du flagrant délit et ne permettent pas d’assurer une bonne relation police-population.</p>
    "
    ref = "Sécurité : retour à la raison - 2017"
    link = "https://avenirencommun.fr/le-livret-securite/"
    tldr = "Restaurer la <strong>police de proximité</strong>. Revenir sur la \"politique du chiffre\". Démenteler la BAC. Rétablir de <strong>bonnes relations police-population</strong>."

  [[categories.list]]
    title = "Effectifs de la police"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "
    • Le recrutement de 5 000 agents administratifs pour libérer policiers et gendarmes aptes à aller sur le terrain et qui travaillent aujourd'hui sur des postes  administratifs ;<br />
    • Le retour des effectifs de policiers et gendarmes à ceux de 2007 (soit le recrutement de 3 000 agents) ;<br />
    • Le doublement des effectifs de la police technique et scientifique (soit l'embauche de 2 000 nouveaux personnels) ;<br />
    • La suppression du statut précaire et peu qualifié des 11 000 adjoints de sécurité en permettant la formation et la titularisation de celles et ceux qui le souhaitent ;
    "
    ref = "Sécurité : retour à la raison - 2017"
    link = "https://avenirencommun.fr/le-livret-securite/"
    tldr = "Recrutement de <strong>5 000 agents administratifs</strong> pour libérer policiers et gendarmes. Recrutement de <strong>3 000 agents</strong> (policiers et gendarmes). Doublement des effectifs de la <strong>police technique et scientifique</strong>. <strong>Suppression</strong> du statut précaire de 11 000 <strong>adjoints de sécurité</strong> par la formation et la titularisation."

  [[categories.list]]
    title = "Équipement de la police"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "
    <p>• Lancer un plan de rénovation et de construction de commissariats de police pour lutter contre la clochardisation du bâti et l'abandon de certains territoires<br />
    • Dotation des services en moyens techniques et matériels suffisants<br />
    • Renouvellement général du parc informatique sous contrainte de sécurité des échanges</p>
    <p>Interdiction immédiate des tasers et flashball.</p>
    "
    ref = "L'Avenir En Commun - 01/12/2016"
    link = "https://laec.fr/s13m3"
    tldr = "Rénovation et construction de <p>commissariats</p>. <p>Dotation</p> des services en moyens suffisants. Renouvellement du <p>parc informatique</p>. Interdiction immédiate des <p>tasers et flashball</p>."

  [[categories.list]]
    title = "Contrôle au faciès"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "Nous  modifierons  la  loi  sur  les  contrôles  d’identité  par  la  police  pour  prendre en compte la récente jurisprudence de la Cour de cassation contre les contrôles au faciès : inversion de la charge de la preuve, réforme de l’article 78-2 du  Code  de  procédure  pénale  pour  rendre  plus  exceptionnels  les  contrôles  d’identité,  obligation  de  délivrance  d’un  récépissé  de  contrôle,  filmage  des  contrôles par la police sous peine de nullité de la procédure qui en découlerait."
    ref = "Sécurité : retour à la raison - 2017"
    link = "https://avenirencommun.fr/le-livret-securite/"
    tldr = "Obligation  de  délivrance  d’un  récépissé  de  contrôle,  filmage  des  contrôles sous peine de nullité."

  [[categories.list]]
    title = "Sans papiers"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "Régulariser les travailleurs sans-papiers pour assurer l'égalité sociale entre travailleurs."
    ref = "L'Avenir En Commun - 01/12/2016"
    link = "https://laec.fr/section/25/eradiquer-la-precarite-respecter-les-metiers-et-les-travailleurs"
    tldr = "Régularisation des travailleurs sans papiers."

  [[categories.list]]
    title = "Prison"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "Garantie du respect des droits des personnes détenues  par le développement du  budget  «réinsertion»  de  l’administration  pénitentiaire,  l’engagement  de  travaux  urgents  de  lutte  contre  l’insalubrité,  la  mise  en  place  d’un  numerus clausus comme mesure transitoire, le respect du droit à l’encellulement individuel, la mise en place de bureaux de vote dans les établissements, le respect du droit du travail pour les détenu·e·s."
    ref = "Une justice au nom du peuple - 2017"
    link = "https://avenirencommun.fr/le-livret-justice/"
    tldr = "Respect des droits des personnes détenues, lutte contre l'insalubrité."

  [[categories.list]]
    title = "Renseignement"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "
    • Renforcement du renseignement territorial et humain.<br />
    • Revenir sur la fusion de la DST et des RG.<br />
    • Privilégier l’infiltration, le travail de terrain et le redéploiement intelligent.<br />
    • Renforcer les moyens d’analyses des renseignements collectés.<br />
    • Recrutement d'analystes et de traducteurs en nombre suffisant.<br />
    • Remise en question des pratiques et dispositifs de surveillance de masse sur l’Internet et les réseaux téléphoniques, inefficaces et liberticides. <br />
    • Focalisation du renseignement sur les menaces sécuritaires et économiques hexagonales, et non sur la surveillance des mouvements sociaux.<br />
    • Restauration de l’indépendance nationale en matière de renseignement, via la fin de la tutelle de fait exercée par les agences anglo-saxonnes.<br />
    "
    ref = "Sécurité : retour à la raison - 2017"
    link = "https://avenirencommun.fr/le-livret-securite/"
    tldr = "Renforcer l'indépendance, le renseignement humain et les moyens d'analyse. Recentrer les missions sur les menaces sécuritaires."

    [[categories.list]]
      title = "Défense militaire"

      [categories.list.them]
      quote = ""
      ref = ""
      link = ""
      tldr = ""

      [categories.list.us]
      quote = "
      <p>Sortir de l'OTAN et refuser la participation de la France à toute alliance militaire permanente à l'exception des opérations de maintien de la paix sous l'égide de l'ONU.</p>
      <p>Rédiger un nouveau Livre blanc et adopter une nouvelle loi de programmation militaire ayant pour objectif la restauration pleine et entière de l'indépendance militaire.</p>
      "
      ref = "L'Avenir En Commun - 01/12/2016"
      link = "https://laec.fr/chapitre/5/pour-l-independance-de-la-france"
      tldr = "Sortie de l'OTAN. Restauration de l'indépendance militaire."

    [[categories.list]]
      title = "Service civique"

      [categories.list.them]
      quote = ""
      ref = ""
      link = ""
      tldr = ""

      [categories.list.us]
      quote = "
      <p>Le service citoyen obligatoire, c’est neuf mois rémunérés au smic et comprenant une formation militaire initiale avec un droit à l’objection de conscience. Ils’appliquera pour les femmes et pour les hommes, sur tout le territoire, y compris dans les départements d’outre-mer, les zones rurales et les quartiers populaires par conscription avant 25 ans. Ce service sera proche du lieu de vie, en limitant le « casernement » aux fonctions qui l’exigent réellement.</p>
      <p>Les jeunes seront affecté·e·s à des tâches d’intérêt général : secours à la population, sapeurs-pompiers, sécurité publique, défense, sécurité civile, protection et réparation de l’environnement, appui à des associations labellisées d’intérêt général. Participer au service citoyen, c’est être au service de soi et au service de tou·te·s.</p>
      <p>Le service citoyen est aussi un moment de remise à niveau gratuite des jeunes qui ont pu décrocher du système scolaire ou qui sont en difficulté. Il comprend en effet un bilan de santé, une évaluation des capacités d’écriture, de lecture et de calcul avec leur éventuelle mise à niveau, mais aussi la formation gratuite à la conduite et le passage de l’examen du permis de conduire.</p>
      <p>Le service citoyen garantira le droit à changer de corps d’affectation en cas de problèmes manifestes. Les jeunes qui le souhaitent pourront aussi rejoindre la garde nationale, placée sous commandement civil.</p>
      "
      ref = "Pour l'émancipation de la jeunesse - 2017"
      link = "https://avenirencommun.fr/le-livret-jeunesse/"
      tldr = "Service citoyen rémunéré et obligatoire de 9 mois."
