[[categories]]
  id = "taxation"
  title = "Fiscalité"

  [[categories.list]]
    title = "Lutte contre la fraude fiscale"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "Supprimer le monopole du déclenchement de poursuites judiciaires par l'administration fiscale en cas de fraude : la justice doit pouvoir enquêter librement et de sa propre initiative, même contre l'avis du ministre."
    ref = "L'Avenir En Commun - 01/12/2016"
    link = "https://laec.fr/s2m2"
    tldr = "Donner à la Justice le droit de déclencher des poursuites fiscales de sa propre initiative."

  [[categories.list]]
    title = "Impôt sur les sociétés"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "Moduler l'impôt sur les sociétés selon l'usage des bénéfices pour encourager l'investissement en France : un taux réduit pour les bénéfices réinvestis en France, un taux plein pour les bénéfices distribués aux actionnaires."
    ref = "L'Avenir En Commun - 01/12/2016"
    link = "https://laec.fr/s20m3"
    tldr = "Instaurer un taux d'imposition réduit pour les entreprises qui réinvestissent leurs bénéfices en France."

  [[categories.list]]
    title = "CICE"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "Transformer les 41 milliards d'euros annuels du pacte de responsabilité et du crédit d'impôt compétitivité (soit 2% du PIB chaque année, 200 milliards d'euros sur un quinquennat) pour financer la transition énergétique et les activités socialement utiles."
    ref = "L'Avenir En Commun - 01/12/2016"
    link = "https://laec.fr/s18m2"
    tldr = "Supprimer le CICE et le réinvestir dans la transition énergétique et les activités socialement utiles."

  [[categories.list]]
    title = "Impôt sur la fortune"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "Renforcer l'ISF"
    ref = "L'Avenir En Commun - 01/12/2016"
    link = "https://laec.fr/s36m4"
    tldr = "Renforcer l'ISF"

  [[categories.list]]
    title = "Impôt sur le revenu (des personnes physiques)"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "
    Refonder l'imposition sur les revenus grâce à un impôt citoyen garantissant les recettes de l'État et celles de la Sécurité sociale et en conservant leur affectation distincte<br />
     • Imposer les revenus du capital comme ceux du travail par une assiette large et unifiée<br />
     • Rendre l'impôt sur les revenus plus progressif avec un barème à 14 tranches contre 5 aujourd'hui : tout le monde doit payer et chacun selon ses moyens réels<br />
     • Instaurer un revenu maximum autorisé : 90% d'impôt pour la tranche au dessus de 20 fois le revenu médian, soit 400 000 euros de revenus annuels (33 000 euros par mois)
    "
    ref = "L'Avenir En Commun - 01/12/2016"
    link = "https://laec.fr/s36m1"
    tldr = "Rendre l'impôt sur les revenus plus progressif avec un barème à 14 tranches contre 5 aujourd'hui."

  [[categories.list]]
    title = "Impôt universel"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "Mettre en place la taxation différentielle permettant de soumettre chaque citoyen français aux impôts français quel que soit son pays de résidence"
    ref = "L'Avenir En Commun - 01/12/2016"
    link = "https://laec.fr/s37m1"
    tldr = "Mettre en place une taxation différentielle quel que soit le pays de résidence."

  [[categories.list]]
    title = "Droits de succession"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "Augmenter les droits de succession sur les gros patrimoines et créer un héritage maximum pour les fortunes les plus importantes (égal au patrimoine des 0,01 % les plus riches, soit 33 millions d'euros en 2012)."
    ref = "L'Avenir En Commun - 01/12/2016"
    link = "https://laec.fr/s36m5"
    tldr = "Augmenter les droits de succession sur les gros patrimoines."

  [[categories.list]]
    title = "TVA"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "Réduire la TVA sur les produits de première nécessité, revenir sur les hausses récentes et réinstaurer une TVA grand luxe pour financer ces baisses."
    ref = "L'Avenir En Commun - 01/12/2016"
    link = "https://laec.fr/s36m6"
    tldr = "Réduire la TVA sur les produits de première nécessité, réinstaurer une TVA grand luxe pour financer ces baisses."

  [[categories.list]]
    title = "Revenus du patrimoine"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "Imposer les revenus du capital comme ceux du travail par une assiette large et unifiée."
    ref = "L'Avenir En Commun - 01/12/2016"
    link = "https://laec.fr/s36m1"
    tldr = "Imposer les revenus du capital comme ceux du travail par une assiette large et unifiée."

  [[categories.list]]
    title = "Niches fiscales"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "Remettre à plat l'ensemble des aides publiques et exonérations d'impôt ou de cotisation accordées aux entreprises, évaluer leur efficacité, et revenir sur les aides antisociales et anti-écologiques."
    ref = "L'Avenir En Commun - 01/12/2016"
    link = ""
    tldr = "Évaluer chacune des niches fiscales et supprimer les niches injustes, inefficaces socialement ou nuisibles écologiquement."

  [[categories.list]]
    title = "Immobilier"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "Imposer les hautes transactions immobilières par une taxe progressive."
    ref = "L'Avenir En Commun - 01/12/2016"
    link = "https://laec.fr/s34m5"
    tldr = "Imposer les hautes transactions immobilières par une taxe progressive."

  [[categories.list]]
    title = "Quotient familial"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "Remplacer l'injuste quotient familial fiscal actuel par un crédit d'impôt par enfant."
    ref = "L'Avenir En Commun - 01/12/2016"
    link = "https://laec.fr/s36m1"
    tldr = "Remplacer le quotient familial par un crédit d'impôt par enfant."

  [[categories.list]]
    title = "Outre-mer"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "Supprimer les exemptions fiscales bénéficiant aux ultra-riches pour les investissements outre-mer (notamment sur l'ISF)."
    ref = "L'Avenir En Commun - 01/12/2016"
    link = "https://laec.fr/s15m3"
    tldr = "Supprimer les exemptions fiscales bénéficiant aux ultra-riches pour les investissements outre-mer (notamment sur l'ISF)."

  [[categories.list]]
    title = "Impôts TPE et PME"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "Refonder l'impôt sur les sociétés pour établir l'égalité devant l'impôt entre PME et grands groupes, instaurer un barème progressif et favoriser l'investissement plutôt que la distribution de dividendes."
    ref = "L'Avenir En Commun - 01/12/2016"
    link = "https://laec.fr/s36m3"
    tldr = "Établir l'égalité devant l'impôt entre PME et grands groupes."

  [[categories.list]]
    title = "Taxe sur les transactions financières"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "
    <p>Instaurer une taxe réelle sur les transactions financières.</p>
    <p>Interdire aux banques françaises toute activité dans les paradis fiscaux en retirant les licences bancaires des établissements récalcitrants.</p>
    "
    ref = "L'Avenir En Commun - 01/12/2016"
    link = "https://laec.fr/section/19/mettre-au-pas-la-finance#mesure-3"
    tldr = "Taxer les transactions financières. Interdire aux banques toute activité dans les paradis fiscaux."
