[[categories]]
  id = "territory"
  title = "Territoire et Transport"

  [[categories.list]]
    title = "Accès aux soins"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "Supprimer les Groupements hospitaliers de territoire (GHT) et reconstruire le maillage des hôpitaux et des maternités de proximité. Il s’agit de garantir la qualité de la prise en charge à toutes les générations et de combler les déserts médicaux par la création d’un corps de médecins généralistes fonctionnaires."
    ref = "Le livret Ruralité et Aménagement du territoire
 - 2017"
    link = "https://avenirencommun.fr/livret-ruralite-amenagement-territoire/"
    tldr = "Combler les déserts médicaux, Créer un corps de médecins généralistes fonctionnaires."

  [[categories.list]]
    title = "Éducation"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "Abroger les « conventions ruralité » qui visent à diminuer le nombre d’écoles en milieu rural pour les remplacer par de grosses structures éloignées des lieux de vie des enfants ; maintenir les écoles à classe unique ; réouvrir les écoles."
    ref = "Le livret Ruralité et Aménagement du territoire
 - 2017"
    link = "https://avenirencommun.fr/livret-ruralite-amenagement-territoire/"
    tldr = "Abroger les \"conventions ruralité\" et réouvrir les écoles."

  [[categories.list]]
    title = "Haut débit"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "Planifier l’accès au haut débit et au très haut débit, avec l’objectif de résorber en priorité les zones blanches. La couverture 4G sera étendue sous l’égide d’un service public du numérique et de la téléphonie."
    ref = "Le livret Ruralité et Aménagement du territoire
 - 2017"
    link = "https://avenirencommun.fr/livret-ruralite-amenagement-territoire/"
    tldr = "Planifier l'accès au haut débit et la couverture 4G de tout le territoire."

  [[categories.list]]
    title = "Services publics"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "
    <p>Défendre et reconstruire le maillage (...) de services publics sur tout le territoire, dans les départements ruraux et les quartiers populaires. </p>
    <p>Faire un moratoire sur les fermetures de services publics et un plan de redéploiement des services publics sur les territoires ruraux et périurbains : services postaux, gares de proximité, hôpitaux et services  de santé, écoles, palais de justice.</p>
    "
    ref = "Le livret Ruralité et Aménagement du territoire
 - 2017"
    link = "https://avenirencommun.fr/livret-ruralite-amenagement-territoire/"
    tldr = "Reconstruire le maillage de services publics sur tout le territoire."

  [[categories.list]]
    title = "Responsabilités et organisation des collectivités"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "
    <p>Reconnaître le principe de libre administration des collectivités, par des communautés de communes choisies et non plus imposées. À l’opposé d’une logique de régionalisation, l’État reprendra le premier rôle de mise en cohérence du développement économique des territoires, dans un objectif d’intérêt général et de transition planifiée et écologique de l’économie.</p>

    <p>Abroger les lois de l’Acte 3 de la décentralisation (loi NOTRe, loi MAPTAM [Modernisation de l'action publique territoriale et d'affirmation des métropoles], loi relative à la délimitation des régions) pour mettre en place une organisation territoriale autour des communes et des départements. Ces collectivités seront le pivot de la construction d’espaces de souveraineté à l’échelle des bassins de vie.</p>
    "
    ref = "Le livret Ruralité et Aménagement du territoire
 - 2017"
    link = "https://avenirencommun.fr/livret-ruralite-amenagement-territoire/"
    tldr = "Donner plus de libertés et de compétences aux collectivités."

  [[categories.list]]
    title = "Dotation des collectivités"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "Refuser les baisses de dotations aux collectivités mises en place par le gouvernement Hollande et garantir une dotation à la hauteur des missions transférées aux collectivités. Il sera également mis fin au remplacement des dotations de l’État par des fonds d’investissement (du type de la DETR [Dotation d'équipement des territoires ruraux] ou des contrats de ruralité). Les collectivités doivent avoir les moyens d’investir mais également des dotations stables en fonctionnement."
    ref = "Le livret Ruralité et Aménagement du territoire
 - 2017"
    link = "https://avenirencommun.fr/livret-ruralite-amenagement-territoire/"
    tldr = "Garantir une dotation à la hauteur des missions transférées aux collectivités."

  [[categories.list]]
    title = "Démocratie et transparence dans les collectivités"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "
    <p>Assurer la transparence des décisions et en finir avec la concentration du pouvoir  dans  les  collectivités  locales.  Le  code  général  des  collectivités  territoriales sera notamment modifié afin de séparer fonctions délibératives et fonctions exécutives. Il s’agit, à travers ces mesures, de garantir le fonctionnement démo-cratique des institutions, les territoires ne devant pas être des baronnies minées par le clientélisme.</p>
    <p>Permettre la participation des citoyen·ne·s aux décisions des collec- tivités par l’instauration de conférences citoyennes de territoire.</p>
    <p>Abroger la loi NOTRe : contre les nouvelles féodalités et l'éloignement du pouvoir des citoyens, refonder l'organisation territoriale de la République et défendre les libertés communales.</p>
    "
    ref = "Le livret Ruralité et Aménagement du territoire
 - 2017"
    link = "https://avenirencommun.fr/livret-ruralite-amenagement-territoire/"
    tldr = "Re-démocratiser le fonctionnement des colléctivités."

  [[categories.list]]
    title = "Aménagement urbain"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "
    <p>Mettre en place un commissariat à l’aménagement du territoire, doté de moyens d’analyse et de planification.</p>
    <p>Promulguer une loi de justice territoriale visant à enrayer la loi du marché (...) et promouvoir la coopération et le développement soutenable et juste de tous les territoires de la République.</p>
    <p>Renforcer le versement pour sous-densité (outil qui permet de lutter contre l’étalement urbain en autorisant l’instauration par les communes d’un seuil minimal de densité par secteur) et planifier le rapprochement des bassins de vie et des bassins d’emploi, afin de stopper l’étalement urbain.</p>
    "
    ref = "Le livret Ruralité et Aménagement du territoire
 - 2017"
    link = "https://avenirencommun.fr/livret-ruralite-amenagement-territoire/"
    tldr = "Promouvoir la coopération et le développement soutenable et juste de tous les territoires de la République."


  [[categories.list]]
    title = "Accès au logement"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "Aussi, afin de rendre le droit au logement réellement effectif, nous l’inscrirons dans la Constitution. Nous sortirons le logement et l’habitat des mécanismes du marché par un plan d’action volontariste qui démarrera dès le début de la mandature."
    ref = "Pour un logement universel et durable - 2017"
    link = "https://avenirencommun.fr/le-livret-logement/"
    tldr = "Inscrire le droit au logement dans la Constitution. Sortir le logement des mécanismes de marché."

  [[categories.list]]
    title = "Transport ferrovière"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "
    <p>Sortir du tout TGV et développer les trains du quotidien (TER et Intercités) ; réouvrir les gares et lignes fermées ; assurer un maillage fin du territoire par la planification intermodale des moyens de déplacement.</p>
    <p>Désobéir aux paquets ferroviaires européens pour bloquer l’ouverture à la concurrence du trafic intérieur des voyageurs prévue en 2023.</p>
    <p>Développer les transports ferroviaires afin d’assurer un maillage adapté aux différentes échelles des territoires. Cela suppose de mettre en œuvre un plan de transport desservant harmonieusement et efficacement l’ensemble des liaisons TER, intercités, TGV. Nous assurerons les liaisons entre aggloméra par des TGV, des trains intercités, des TER et des trams-trains efficaces. </p>
    "
    ref = "Pour des transports écologiques et accessibles - 2017"
    link = "https://avenirencommun.fr/le-livret-transports/"
    tldr = "Développer les transports ferroviaires afin d’assurer un maillage adapté aux différentes échelles des territoires."

  [[categories.list]]
    title = "Transport de marchandises"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "
    <p>Nous organiserons, en différents lieux de l’agglomération (gare, nœud autoroutier, sortie d’autoroute, port) des centres de distribution urbaine, bases logistiques de tri, de stockage, éventuellement de vente, où s’opérera cette rupture de charge. À partir de ces centres, nous mettrons en place une logistique « du dernier kilomètre » par toutes sortes de modes non polluants (camions au gaz naturel, camionnettes électriques, tramways de fret, triporteurs à assistance électrique). Pour les produits frais, issus de l’agriculture et de l’élevage, une logistique particulière de proximité sera mise en place, favorisant les circuits courts de distribution, avec des véhicules non-polluants.</p>
    <p>Nous relancerons le transport de fret par voie ferrée, en particulier grâce au développement du transport combiné rail-route et du ferroutage (camions mis sur les trains), afin de réduire la part du transport routier des marchandises. Nous lancerons ainsi un grand plan ferroutage avec comme objectif que tous les camions traversant notre pays entre la frontière belge et la frontière espagnole passent sur des trains.</p>
    <p>Le transport fluvial est le moins polluant à la tonne transportée, (...). Nous favoriserons des investissements et des innovations dans ce mode de transports, en rénovant les infrastructures fluviales existantes, et en augmentant leurs capacités. Le transport fluvial devra être systématiquement relié aux ports maritimes.</p>
    "
    ref = "Pour des transports écologiques et accessibles - 2017"
    link = "https://avenirencommun.fr/le-livret-transports/"
    tldr = "Remplacer le transport par camions par plusieurs alternatives comme ferroutage, transport fluvial, triporteurs à assistance électrique ..."

  [[categories.list]]
    title = "Autoroutes"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "
    <p>Nationaliser les autoroutes.</p>
    <p>Garantir la responsabilité de l’État dans la gestion et l’entretien des routes nationales. L’enveloppe budgétaire ainsi économisée par les régions sera réattribuée à la création de stations d’alimentation en énergies propres pour les véhicules. Nous mettrons de cette manière en œuvre les conditions de mutation du parc automobile vers les énergies propres (électricité et gaz). </p>
    "
    ref = "Pour des transports écologiques et accessibles - 2017"
    link = "https://avenirencommun.fr/le-livret-transports/"
    tldr = "Re-nationaliser les autoroutes."

  [[categories.list]]
    title = "Covoiturage"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "Favoriser le co-voiturage, l’autopartage et le transport à la demande."
    ref = "Pour des transports écologiques et accessibles - 2017"
    link = "https://avenirencommun.fr/le-livret-transports/"
    tldr = "Favoriser le co-voiturage, l’autopartage et le transport à la demande."

  [[categories.list]]
    title = "Diesel"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "
    <p>Organiser un plan de sortie rapide du diesel en ville.</p>
    <p>Supprimer progressivement les avantages fiscaux liés au diesel pour les flottes d’entreprises.</p>
    "
    ref = "Pour des transports écologiques et accessibles - 2017"
    link = "https://avenirencommun.fr/le-livret-transports/"
    tldr = "Sortie rapide du diesel en ville et suppression des avantages fiscaux pour les flottes d'entreprises."

  [[categories.list]]
    title = "Vélo"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "
    <p>Soutenir les formules combinant le vélo et le TER, essentielles dans le cadre des déplacements domicile-travail : dans les régions qui ont fait ce choix, les quantités de CO2 émis ont drastiquement baissé.</p>
    <p>Mettre en place une politique nationale en faveur du vélo et du vélo à assistance électrique (VAE) cohérente du national au local et suivie sur le long terme. Une attention toute particulière sera portée à l’intermodalité entre vélo et transports collectifs.</p>
    <p>Nous réaliserons des itinéraires cyclables pour relier les communes entre elles, comme c’est déjà le cas dans certains pays d’Europe (Pays-Bas, Danemark, Suisse). Les liaisons cyclables aux gares proches des parcours seront systématiques. Nous appuierons la réalisation de voies vertes et de véloroutes, appréciées de nos concitoyens comme des touristes étrangers, pour leurs loisirs et leurs vacances.</p>
    "
    ref = "Pour des transports écologiques et accessibles - 2017"
    link = "https://avenirencommun.fr/le-livret-transports/"
    tldr = "Favoriser le vélo et l'intermodalité entre vélo et transports collectifs."

  [[categories.list]]
    title = "Notre-Dame-des-Landes"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "
    Nous arrêterons immédiatement le projet de l’aéroport de Notre-Dame-des- Landes (NDDL). L’aéroport Nantes-Atlantique peut être agrandi. Les 1600 hectares prévus pour NDDL sont utiles à la préservation des écosystèmes et de l’agriculture biologique et paysanne.
    "
    ref = "Pour des transports écologiques et accessibles - 2017"
    link = "https://avenirencommun.fr/le-livret-transports/"
    tldr = "Arrêt immédiat du projet d'aéroport Notre-Dame-des- Landes."
