[[categories]]
  id = "work"
  title = "Travail et Entreprises"

  [[categories.list]]
    title = ""

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "
    <p>
    Appliquer réellement et immédiatement les 35 heures :<br />
    • Majorer les heures supplémentaires (25 % pour les 4 premières et 50 % et plus au-delà)<br />
    • Revenir sur la flexibilisation, l'annualisation, l'intensification et les horaires fractionnés<br />
    • Revenir sur le forfait-jour et le limiter aux seuls cadres dirigeants<br />
    • Revenir sur les élargissements du travail du dimanche
    </p>
    <p>Convoquer une conférence nationale sur le partage du temps de travail et l'impact du progrès technologique, favoriser le passage à la semaine de quatre jours pour aller vers les 32 heures et appliquer les 32 heures pour les salariés en travail de nuit et les métiers pénibles
    </p>
    "
    ref = "L'Avenir En Commun - 01/12/2016"
    link = "https://laec.fr/section/28/reduire-le-temps-de-travail-travailler-moins-pour-travailler-tous"
    tldr = "Application réelle et immédiate des 35 heures. Favoriser le passage à la semaine de quatre jours."

  [[categories.list]]
    title = "Loi El Khomri"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "La loi El Khomri a mis fin à la hiérarchie des normes sociales. Désormais, un accord d'entreprise peut s'imposer même si un accord de branche ou la loi sont plus favorables aux salariés."
    ref = "L'Avenir En Commun - 01/12/2016"
    link = "https://laec.fr/section/24/abroger-la-loi-el-khomri"
    tldr = "Abrogation la loi El Khomri."

  [[categories.list]]
    title = "Rupture conventionnelle"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "Refonder le recours à la rupture conventionnelle pour empêcher les licenciements déguisés."
    ref = "L'Avenir En Commun - 01/12/2016"
    link = "https://laec.fr/section/23/empecher-les-licenciements-boursiers-dans-l-entreprise-pour-conserver-et-developper-l-emploi"
    tldr = "Refonder le recours à la rupture conventionnelle pour empêcher les licenciements déguisés."

  [[categories.list]]
    title = "Contrat de travail"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "Réaffirmer dans les faits le CDI comme norme du contrat de travail."
    ref = "L'Avenir En Commun - 01/12/2016"
    link = "https://laec.fr/section/25/eradiquer-la-precarite-respecter-les-metiers-et-les-travailleurs"
    tldr = "Réaffirmer dans les faits le CDI comme norme du contrat de travail."

  [[categories.list]]
    title = "Travail détaché"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "Cesser d'appliquer unilatéralement la directive sur le détachement de travailleurs en France : la législation nationale doit s'appliquer totalement, y compris concernant les cotisations sociales patronales et salariales."
    ref = "L'Avenir En Commun - 01/12/2016"
    link = "https://laec.fr/section/49/prendre-les-mesures-immediates-et-unilaterales-de-sauvegarde-des-interets-de-la-nation-et-d-application-de-notre-projet"
    tldr = "Arrêt unilatéral de l'application de la directive sur le détachement des travailleurs en France."

  [[categories.list]]
    title = "Démocratie dans l'entreprise"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "Accorder un droit de veto suspensif aux comités d'entreprise sur les plans de licenciements, réformer les tribunaux de commerce et les procédures de redressement et liquidation d'entreprise pour donner plus de pouvoirs aux salariés et à leurs représentants, refondre la procédure judiciaire de contestation des licenciements économiques pour qu'ils ne puissent être effectifs avant épuisement des recours."
    ref = "L'Avenir En Commun - 01/12/2016"
    link = "https://laec.fr/section/23/empecher-les-licenciements-boursiers-dans-l-entreprise-pour-conserver-et-developper-l-emploi"
    tldr = "Droit de véto suspensif pour les CE sur les plans de licenciements et réforme pour donner plus de pouvoir aux salariés."

  [[categories.list]]
    title = "Pension retraite"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "
    <p>Revaloriser les pensions de retraite au niveau du smic pour une carrière complète et porter le minimum vieillesse au niveau du seuil de pauvreté.</p>
    <p>Assurer le financement durable des régimes de retraites solidaires, intergénérationnelles et par répartition, par la mise en contribution des revenus financiers des entreprises, par l'augmentation du nombre de cotisants et de l'assiette des cotisations (créations d'emplois, hausse des salaires, recul de la précarité, hausse de l'activité des femmes, etc.) et de leur taux, la fin des exonérations fiscales pour les régimes de retraite par capitalisation.</p>
    "
    ref = "L'Avenir En Commun - 01/12/2016"
    link = "https://laec.fr/section/31/restaurer-le-droit-a-la-retraite-a-60-ans-augmenter-les-petites-pensions"
    tldr = "Revalorisation des \"petites\" retraites, pérénnisation du financement des retraites."

  [[categories.list]]
    title = "Âge de départ à la retraite"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "Restaurer le droit à la retraite à 60 ans à taux plein, ramener la durée de cotisation pour une retraite complète à quarante ans."
    ref = "L'Avenir En Commun - 01/12/2016"
    link = "https://laec.fr/section/31/restaurer-le-droit-a-la-retraite-a-60-ans-augmenter-les-petites-pensions"
    tldr = "Restaurer le droit à la retraite à 60 ans et 40 annuités de cotisation."

  [[categories.list]]
    title = "Syndicats"

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = "Mettre fin à l'usurpation par le Medef de la parole des chefs d'entreprise : fonder la représentativité des organisations patronales sur la base d'élections, comme c'est déjà le cas pour les syndicats de salariés."
    ref = "L'Avenir En Commun - 01/12/2016"
    link = "https://laec.fr/section/2/balayer-l-oligarchie-abolir-les-privileges-de-la-caste"
    tldr = "Représentativité des organisation partonales sur la base d'élections."

  [[categories.list]]
    title = ""

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = ""
    ref = "L'Avenir En Commun - 01/12/2016"
    link = ""
    tldr = ""

  [[categories.list]]
    title = ""

    [categories.list.them]
    quote = ""
    ref = ""
    link = ""
    tldr = ""

    [categories.list.us]
    quote = ""
    ref = "L'Avenir En Commun - 01/12/2016"
    link = ""
    tldr = ""
